export default [
  {
    login: "heitor-lassarote",
    id: 30162364,
    node_id: "MDQ6VXNlcjMwMTYyMzY0",
    avatar_url: "https://avatars.githubusercontent.com/u/30162364?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/heitor-lassarote",
    html_url: "https://github.com/heitor-lassarote",
    followers_url: "https://api.github.com/users/heitor-lassarote/followers",
    following_url: "https://api.github.com/users/heitor-lassarote/following{/other_user}",
    gists_url: "https://api.github.com/users/heitor-lassarote/gists{/gist_id}",
    starred_url: "https://api.github.com/users/heitor-lassarote/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/heitor-lassarote/subscriptions",
    organizations_url: "https://api.github.com/users/heitor-lassarote/orgs",
    repos_url: "https://api.github.com/users/heitor-lassarote/repos",
    events_url: "https://api.github.com/users/heitor-lassarote/events{/privacy}",
    received_events_url: "https://api.github.com/users/heitor-lassarote/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "githubfollow",
    id: 67248948,
    node_id: "MDQ6VXNlcjY3MjQ4OTQ4",
    avatar_url: "https://avatars.githubusercontent.com/u/67248948?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/githubfollow",
    html_url: "https://github.com/githubfollow",
    followers_url: "https://api.github.com/users/githubfollow/followers",
    following_url: "https://api.github.com/users/githubfollow/following{/other_user}",
    gists_url: "https://api.github.com/users/githubfollow/gists{/gist_id}",
    starred_url: "https://api.github.com/users/githubfollow/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/githubfollow/subscriptions",
    organizations_url: "https://api.github.com/users/githubfollow/orgs",
    repos_url: "https://api.github.com/users/githubfollow/repos",
    events_url: "https://api.github.com/users/githubfollow/events{/privacy}",
    received_events_url: "https://api.github.com/users/githubfollow/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "rogerlog",
    id: 7367927,
    node_id: "MDQ6VXNlcjczNjc5Mjc=",
    avatar_url: "https://avatars.githubusercontent.com/u/7367927?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/rogerlog",
    html_url: "https://github.com/rogerlog",
    followers_url: "https://api.github.com/users/rogerlog/followers",
    following_url: "https://api.github.com/users/rogerlog/following{/other_user}",
    gists_url: "https://api.github.com/users/rogerlog/gists{/gist_id}",
    starred_url: "https://api.github.com/users/rogerlog/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/rogerlog/subscriptions",
    organizations_url: "https://api.github.com/users/rogerlog/orgs",
    repos_url: "https://api.github.com/users/rogerlog/repos",
    events_url: "https://api.github.com/users/rogerlog/events{/privacy}",
    received_events_url: "https://api.github.com/users/rogerlog/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "jonascavalcante",
    id: 53956504,
    node_id: "MDQ6VXNlcjUzOTU2NTA0",
    avatar_url: "https://avatars.githubusercontent.com/u/53956504?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/jonascavalcante",
    html_url: "https://github.com/jonascavalcante",
    followers_url: "https://api.github.com/users/jonascavalcante/followers",
    following_url: "https://api.github.com/users/jonascavalcante/following{/other_user}",
    gists_url: "https://api.github.com/users/jonascavalcante/gists{/gist_id}",
    starred_url: "https://api.github.com/users/jonascavalcante/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/jonascavalcante/subscriptions",
    organizations_url: "https://api.github.com/users/jonascavalcante/orgs",
    repos_url: "https://api.github.com/users/jonascavalcante/repos",
    events_url: "https://api.github.com/users/jonascavalcante/events{/privacy}",
    received_events_url: "https://api.github.com/users/jonascavalcante/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "Octavio-Pedro",
    id: 27983779,
    node_id: "MDQ6VXNlcjI3OTgzNzc5",
    avatar_url: "https://avatars.githubusercontent.com/u/27983779?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Octavio-Pedro",
    html_url: "https://github.com/Octavio-Pedro",
    followers_url: "https://api.github.com/users/Octavio-Pedro/followers",
    following_url: "https://api.github.com/users/Octavio-Pedro/following{/other_user}",
    gists_url: "https://api.github.com/users/Octavio-Pedro/gists{/gist_id}",
    starred_url: "https://api.github.com/users/Octavio-Pedro/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Octavio-Pedro/subscriptions",
    organizations_url: "https://api.github.com/users/Octavio-Pedro/orgs",
    repos_url: "https://api.github.com/users/Octavio-Pedro/repos",
    events_url: "https://api.github.com/users/Octavio-Pedro/events{/privacy}",
    received_events_url: "https://api.github.com/users/Octavio-Pedro/received_events",
    type: "User",
    site_admin: false
    },
    {
    login: "adahra",
    id: 6745098,
    node_id: "MDQ6VXNlcjY3NDUwOTg=",
    avatar_url: "https://avatars.githubusercontent.com/u/6745098?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/adahra",
    html_url: "https://github.com/adahra",
    followers_url: "https://api.github.com/users/adahra/followers",
    following_url: "https://api.github.com/users/adahra/following{/other_user}",
    gists_url: "https://api.github.com/users/adahra/gists{/gist_id}",
    starred_url: "https://api.github.com/users/adahra/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/adahra/subscriptions",
    organizations_url: "https://api.github.com/users/adahra/orgs",
    repos_url: "https://api.github.com/users/adahra/repos",
    events_url: "https://api.github.com/users/adahra/events{/privacy}",
    received_events_url: "https://api.github.com/users/adahra/received_events",
    type: "User",
    site_admin: false
  }
]
