export default {
  login: "Jarlei3m",
  id: 59893310,
  node_id: "MDQ6VXNlcjU5ODkzMzEw",
  avatar_url: "https://avatars.githubusercontent.com/u/59893310?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/Jarlei3m",
  html_url: "https://github.com/Jarlei3m",
  followers_url: "https://api.github.com/users/Jarlei3m/followers",
  following_url: "https://api.github.com/users/Jarlei3m/following{/other_user}",
  gists_url: "https://api.github.com/users/Jarlei3m/gists{/gist_id}",
  starred_url: "https://api.github.com/users/Jarlei3m/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/Jarlei3m/subscriptions",
  organizations_url: "https://api.github.com/users/Jarlei3m/orgs",
  repos_url: "https://api.github.com/users/Jarlei3m/repos",
  events_url: "https://api.github.com/users/Jarlei3m/events{/privacy}",
  received_events_url: "https://api.github.com/users/Jarlei3m/received_events",
  type: "User",
  site_admin: false,
  name: "Járlei Rodrigues",
  company: null,
  blog: "https://www.linkedin.com/in/jarleirodrigues/",
  location: "Rio de Janeiro, Brazil",
  email: null,
  hireable: true,
  bio: "Beginner at web development, but passionate about it! Code addict, aways looking for the next level! 👨‍💻",
  twitter_username: null,
  public_repos: 62,
  public_gists: 0,
  followers: 6,
  following: 9,
  created_at: "2020-01-14T20:01:23Z",
  updated_at: "2021-01-26T21:04:54Z"
}